# This workflow will build a Java project with Maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "30 1 * * *"
#   - cron: '*/10 * * * *'    #run every 10 minutes. 
  

jobs:
  build:
    runs-on: ubuntu-latest
#     runs-on: macos-latest
#     runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Install Chrome    
      run: |
       sudo apt install google-chrome-stable
    - name: Install Google Chrome Using Shell  Script 
      run: |
       chmod +x ./myScripts/InstallChrome.sh
        ./myScripts/InstallChrome.sh    
  
#     - name: Run Security Checks
#       run: bash myScripts/security_checks.sh
  
    - name: Build with Maven
      run: mvn test -q
      
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Automation-test-reports
        path: |
          target/
          Logs/

#     - name: Security Check Results
#       uses: actions/upload-artifact@v2
#       with:
#         name: security-check-report
#         path: 
#           security_checks_log.txt
