# This workflow will build a Java project with Maven

name: Java CI with Maven

on:
  push:
    branches: [ codecoverage_actions ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "30 1 * * *"
#   - cron: '*/10 * * * *'    #run every 10 minutes. 
  
env:
  UNIT_TESTS_REPORT_FILENAME: "jacoco-reports-${{ github.run_id }}"
  REQUIRED_CODE_COVERAGE_PERCENT: 80
#   SONAR_SCANNER_VERSION: 4.6.1.2450


jobs:
  build:
    runs-on: ubuntu-latest
#     runs-on: macos-latest
#     runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Install Chrome    
      run: |
       sudo apt install google-chrome-stable
#     - name: Install Google Chrome Using Shell  Script 
#       run: |
#        chmod +x ./myScripts/InstallChrome.sh
#         ./myScripts/InstallChrome.sh    
  
#     - name: Run Security Checks
#       run: bash myScripts/security_checks.sh
  
    - name: Install xmllint tool
      shell: bash
      run: |
        sudo apt-get install libxml2-utils
    - name: Setup sonar scanner
      uses: warchant/setup-sonar-scanner@v3


    - name: Build with Maven
      run: mvn test -q
      
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Automation-test-reports
        path: |
          target/
          Logs/

#     - name: Security Check Results
#       uses: actions/upload-artifact@v2
#       with:
#         name: security-check-report
#         path: 
#           security_checks_log.txt
