# This workflow will build a Java project with Maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "30 1 * * *"
#   - cron: '*/10 * * * *'    #run every 10 minutes. 
  

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains('refs/heads/master refs/heads/develop',github.ref || startsWith(github.ref, 'refs/tags/v')
#     runs-on: macos-latest
#     runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v2
    
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
        
      
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.6.3
      
    - name: Set Maven Environment Variables
      uses: allenevans/set-env@v2.0.1
      with:
        M2_HOME: /opt/hostedtoolcache/maven/3.6.3/x64
           
        
    - name: Install Chrome    
      run: |
       sudo apt install google-chrome-stable
#        sudo apt --fix-broken install
#        sudo apt install maven -y

#     - name: Install Google Chrome Using Shell  Script 
#       run: |
#        chmod +x ./myScripts/InstallChrome.sh
#         ./myScripts/InstallChrome.sh    
  
#     - name: Run Security Checks
#       run: bash myScripts/security_checks.sh
  
    - name: Build with Maven
      run: mvn test -q
      
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Automation-test-reports
        path: |
          target/
          Logs/

#     - name: Security Check Results
#       uses: actions/upload-artifact@v2
#       with:
#         name: security-check-report
#         path: 
#           security_checks_log.txt

