# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Install Google Chrome Using Shell Script
      run: |
       chmod +x ./Scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh  
        
#     - run: mkdir target      
    - name: Build with Maven
      run: mvn test -q --file pom.xml
      
#     - run: mkdir test-artifacts && cp target/*.* test-artifacts
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/*.*
              
#     - name: Download a Single Artifact
#       uses: actions/download-artifact@v2 
#       with:
#        name: test-reports
     

#     - name: Download all workflow run artifacts
#       uses: actions/download-artifact@v2
